name: "`fast-crystal` benchmarks"
on:
  push:
    paths:
      - .github/workflows/benchmark.yml

jobs:
  todo-issues:
    runs-on: ubuntu-latest
    name: Benchmark ${{ matrix.crystal }}
    strategy:
      fail-fast: false
      matrix:
        crystal:
          - 0.36.1
          - 1.0.0
          - 1.1.1
          - 1.2.2
          - 1.3.2
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1.6.0
        with:
          crystal: ${{ matrix.crystal }}
      - run: |
          git clone https://github.com/icyleaf/fast-crystal
          cd fast-crystal
          make run
